# Generated by Django 4.0.5 on 2022-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
