# Generated by Django 4.0.5 on 2022-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pollmodel_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollmodel',
            old_name='public',
            new_name='isPublic',
        ),
        migrations.AddField(
            model_name='pollmodel',
            name='isSingleSelection',
            field=models.BooleanField(default=True),
        ),
    ]
