# Generated by Django 4.0.5 on 2022-08-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_public_pollmodel_ispublic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollmodel',
            old_name='isSingleSelection',
            new_name='isMultipleSelectionsAllowed',
        ),
    ]
