# Generated by Django 4.0.5 on 2022-08-02 14:13

import dashboard.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_isselectioneditable_pollmodel_isselectionchangeable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=dashboard.fields.PollOptionField(), size=None),
        ),
    ]
