# Generated by Django 4.0.5 on 2022-08-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipvoteregistry',
            name='voteOptionStr',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='uservoteregistry',
            name='voteOptionStr',
            field=models.CharField(default='', max_length=150),
        ),
    ]
